/**
 * File purpose: Lists, filters, exports, and starts management-of-change review records.
 * Fallback/error behavior: Query and RPC failures are surfaced without discarding the current register state.
 * Known limitation: Filtering and exports operate on records loaded for the current organization and session.
 */
import { type FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { supabase } from '../../../lib/supabase';
import { csvCell, formatMocName, mocChangeTypes, mocSources, mocStatuses } from '../lib/management-of-change';

type Moc = { id:string; moc_number:number; title:string; source:string; change_type:string; status:string; created_at:string; approved_at:string|null; completed_at:string|null; initiated_by:string; safety_reviewer_id:string|null; operational_capabilities:{name:string}|null; equipment:{name:string}|null };
const blank = { title:'', description:'', source:'Manual', changeType:'Other safety-relevant change', capabilityName:'', equipmentId:'', safetyEventId:'' };

export function MocRegisterPage() {
  const navigate = useNavigate();
  const [records,setRecords]=useState<Moc[]>([]); const [equipment,setEquipment]=useState<{id:string;name:string}[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState(blank);
  const [filters,setFilters]=useState({from:'',to:'',source:'All',type:'All',status:'All',capability:'',equipment:'',person:''}); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  async function load(){ const [m,e]=await Promise.all([supabase.from('management_of_change').select('id,moc_number,title,source,change_type,status,created_at,approved_at,completed_at,initiated_by,safety_reviewer_id,operational_capabilities(name),equipment(name)').order('created_at',{ascending:false}),supabase.from('equipment').select('id,name').order('name')]); if(m.error||e.error)setError(m.error?.message||e.error?.message||'Unable to load MOC register.'); else {setRecords((m.data||[]) as unknown as Moc[]);setEquipment(e.data||[]);} }
  useEffect(()=>{void load();},[]);
  const filtered=useMemo(()=>records.filter(r=>(!filters.from||r.created_at.slice(0,10)>=filters.from)&&(!filters.to||r.created_at.slice(0,10)<=filters.to)&&(filters.source==='All'||r.source===filters.source)&&(filters.type==='All'||r.change_type===filters.type)&&(filters.status==='All'||r.status===filters.status)&&(!filters.capability||r.operational_capabilities?.name.toLowerCase().includes(filters.capability.toLowerCase()))&&(!filters.equipment||r.equipment?.name.toLowerCase().includes(filters.equipment.toLowerCase()))&&(!filters.person||[r.initiated_by,r.safety_reviewer_id].some(v=>v?.toLowerCase().includes(filters.person.toLowerCase())))),[records,filters]);
  async function start(event:FormEvent){event.preventDefault();setBusy(true);setError(null);const {data,error}=await supabase.rpc('start_management_of_change',{change_title:form.title.trim(),change_description:form.description.trim(),change_source:form.source,requested_change_type:form.changeType,linked_equipment_id:form.equipmentId||null,linked_safety_event_id:form.safetyEventId||null,capability_name:form.capabilityName.trim()||null,linked_capability_id:null});setBusy(false);if(error)return setError(error.message);navigate(`/sms/moc/${String((data as {id:string}).id)}`);}
  function exportRegister(all=false){const rows=all?records:filtered;const csv=[['MOC','Capability','Equipment','Source','Change type','Status','Date opened','Date approved','Date completed','Initiator','Reviewer'],...rows.map(r=>[formatMocName(r.moc_number,r.title),r.operational_capabilities?.name,r.equipment?.name,r.source,r.change_type,r.status,r.created_at,r.approved_at,r.completed_at,r.initiated_by,r.safety_reviewer_id])].map(row=>row.map(csvCell).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=all?'all-management-of-change-records.csv':'management-of-change-register.csv';a.click();URL.revokeObjectURL(a.href);}
  return <section className="space-y-4"><header className="flex flex-wrap items-start justify-between gap-3"><div><Link to="/sms" className="text-sm font-semibold text-brand-700">Back to SMS</Link><h1 className="mt-2 text-2xl font-semibold text-brand-900">Management of Change Register</h1><p className="mt-1 text-sm text-slate-600">Permanent organizational history of safety-relevant change reviews.</p></div><button onClick={()=>setOpen(true)} className="rounded-lg bg-brand-700 px-4 py-2 text-sm font-semibold text-white">Start Change Review</button></header>
  {error?<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>:null}
  {open?<form onSubmit={start} className="rounded-xl border border-brand-200 bg-brand-50 p-4"><div className="flex justify-between"><h2 className="font-semibold text-brand-900">Start Change Review</h2><button type="button" onClick={()=>setOpen(false)}>Close</button></div><div className="mt-3 grid gap-3 sm:grid-cols-2"><Field label="Change title" value={form.title} change={title=>setForm({...form,title})} required/><label className="text-sm font-medium text-slate-700">Source<select className="mt-1 w-full rounded-lg border p-2" value={form.source} onChange={e=>setForm({...form,source:e.target.value})}>{mocSources.map(x=><option key={x}>{x}</option>)}</select></label><label className="text-sm font-medium text-slate-700">Change type<select className="mt-1 w-full rounded-lg border p-2" value={form.changeType} onChange={e=>setForm({...form,changeType:e.target.value})}>{mocChangeTypes.map(x=><option key={x}>{x}</option>)}</select></label><Field label="Affected capability (optional)" value={form.capabilityName} change={capabilityName=>setForm({...form,capabilityName})}/><label className="text-sm font-medium text-slate-700">Linked equipment (optional)<select className="mt-1 w-full rounded-lg border p-2" value={form.equipmentId} onChange={e=>setForm({...form,equipmentId:e.target.value})}><option value="">None</option>{equipment.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></label><label className="sm:col-span-2 text-sm font-medium text-slate-700">Change description<textarea className="mt-1 min-h-24 w-full rounded-lg border p-2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><button disabled={busy||!form.title.trim()} className="mt-3 rounded-lg bg-brand-700 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{busy?'Starting…':'Start Change Review'}</button></form>:null}
  <article className="rounded-xl border bg-white p-4 shadow-sm"><div className="grid gap-2 sm:grid-cols-4"><input type="date" aria-label="From date" className="rounded-lg border p-2" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/><input type="date" aria-label="To date" className="rounded-lg border p-2" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/><Select label="Source" value={filters.source} values={mocSources} change={source=>setFilters({...filters,source})}/><Select label="Status" value={filters.status} values={mocStatuses} change={status=>setFilters({...filters,status})}/><Select label="Change type" value={filters.type} values={mocChangeTypes} change={type=>setFilters({...filters,type})}/><input placeholder="Capability" className="rounded-lg border p-2" value={filters.capability} onChange={e=>setFilters({...filters,capability:e.target.value})}/><input placeholder="Aircraft or equipment" className="rounded-lg border p-2" value={filters.equipment} onChange={e=>setFilters({...filters,equipment:e.target.value})}/><input placeholder="Initiator or reviewer ID" className="rounded-lg border p-2" value={filters.person} onChange={e=>setFilters({...filters,person:e.target.value})}/></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>exportRegister()} className="rounded-lg border px-3 py-2 text-sm font-semibold">Export MOC register</button><button onClick={()=>exportRegister(true)} className="rounded-lg border px-3 py-2 text-sm font-semibold">Export all Management of Change records</button></div></article>
  <div className="overflow-x-auto rounded-xl border bg-white shadow-sm"><table className="min-w-full text-left text-sm"><thead className="bg-slate-50 text-slate-600"><tr>{['MOC display name','Affected capability','Source','Change type','Status','Date opened','Date approved','Date completed','Initiator / reviewer'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t"><td className="p-3 font-semibold"><Link className="text-brand-700" to={`/sms/moc/${r.id}`}>{formatMocName(r.moc_number,r.title)}</Link></td><td className="p-3">{r.operational_capabilities?.name||'—'}</td><td className="p-3">{r.source}</td><td className="p-3">{r.change_type}</td><td className="p-3">{r.status}</td><td className="p-3">{new Date(r.created_at).toLocaleDateString()}</td><td className="p-3">{r.approved_at?new Date(r.approved_at).toLocaleDateString():'—'}</td><td className="p-3">{r.completed_at?new Date(r.completed_at).toLocaleDateString():'—'}</td><td className="p-3 text-xs">{r.safety_reviewer_id||r.initiated_by}</td></tr>)}</tbody></table>{!filtered.length?<p className="p-6 text-center text-sm text-slate-500">No change reviews match these filters.</p>:null}</div></section>;
}
function Field({label,value,change,required=false}:{label:string;value:string;change:(v:string)=>void;required?:boolean}){return <label className="text-sm font-medium text-slate-700">{label}<input required={required} className="mt-1 w-full rounded-lg border p-2" value={value} onChange={e=>change(e.target.value)}/></label>}
function Select({label,value,values,change}:{label:string;value:string;values:readonly string[];change:(v:string)=>void}){return <select aria-label={label} className="rounded-lg border p-2" value={value} onChange={e=>change(e.target.value)}><option>All</option>{values.map(x=><option key={x}>{x}</option>)}</select>}
