-- Integrate Personnel snapshots into Proposal creation and prepare Proposal -> Job handoff.

alter table public.personnel
  add column if not exists professional_bio text,
  add column if not exists certifications_summary text,
  add column if not exists profile_photo_url text;

comment on column public.personnel.professional_bio is 'Multi-line professional biography used to auto-populate proposal RPIC snapshots.';
comment on column public.personnel.certifications_summary is 'Multi-line certifications and credentials summary used to auto-populate proposal RPIC snapshots.';
comment on column public.personnel.profile_photo_url is 'Future-use profile image URL or upload placeholder for personnel records.';

alter table public.proposals
  add column if not exists proposal_number text,
  add column if not exists proposed_rpic_id uuid references public.personnel(id) on delete set null,
  add column if not exists proposed_rpic_name text,
  add column if not exists proposed_rpic_credentials text,
  add column if not exists proposed_rpic_bio text;

create index if not exists proposals_proposal_number_idx on public.proposals(proposal_number);
create index if not exists proposals_proposed_rpic_id_idx on public.proposals(proposed_rpic_id);

comment on column public.proposals.proposal_number is 'Human-readable proposal number generated by the application for proposal-to-job handoff.';
comment on column public.proposals.proposed_rpic_id is 'Selected personnel record ID for the proposed RPIC at proposal creation time.';
comment on column public.proposals.proposed_rpic_name is 'Snapshot of the selected RPIC name at proposal creation time.';
comment on column public.proposals.proposed_rpic_credentials is 'Snapshot of the selected RPIC certifications summary at proposal creation time.';
comment on column public.proposals.proposed_rpic_bio is 'Snapshot of the selected RPIC professional bio at proposal creation time.';

alter table public.jobs
  add column if not exists source_proposal_id uuid references public.proposals(id) on delete set null,
  add column if not exists source_proposal_number text,
  add column if not exists client_name text,
  add column if not exists contact_name text,
  add column if not exists client_phone text,
  add column if not exists client_email text,
  add column if not exists site_address text,
  add column if not exists preliminary_hazards jsonb not null default '[]'::jsonb,
  add column if not exists proposed_rpic_id uuid references public.personnel(id) on delete set null,
  add column if not exists proposed_rpic_name text,
  add column if not exists proposed_rpic_credentials text,
  add column if not exists proposed_rpic_bio text;

create index if not exists jobs_source_proposal_id_idx on public.jobs(source_proposal_id);
create index if not exists jobs_proposed_rpic_id_idx on public.jobs(proposed_rpic_id);

comment on column public.jobs.source_proposal_id is 'Proposal record that was converted into this job, if applicable.';
comment on column public.jobs.source_proposal_number is 'Proposal number carried forward from the source proposal.';
comment on column public.jobs.client_name is 'Client name carried forward from the source proposal for mission planning context.';
comment on column public.jobs.site_address is 'Site address carried forward from the source proposal for mission planning context.';
comment on column public.jobs.preliminary_hazards is 'Preliminary proposal hazard assessment carried into the job for later JHA refinement.';
comment on column public.jobs.proposed_rpic_id is 'Proposed RPIC personnel ID carried forward from the source proposal; later crew assignments remain editable in JHA.';
